version: "2"

services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/1.9/Dockerfile
        depends_on:
            - php
            - fluentd
        volumes:
            - symfony_volume:/var/www/symfony
            - nginx_volume:/var/lib/nginx
        ports:
            - $SYMDOCK_NGINX_PORT:80
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
                tag: "nginx.docker.{{.Name }}"
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    php:
        build:
            context: .
            dockerfile: ./php/5.6/Dockerfile
            #dockerfile: ./php/7/Dockerfile
            #dockerfile: ./hhvm/latest/Dockerfile
        depends_on:
            - mysql
            - elasticsearch
            - rabbitmq
            - memcached
            - fluentd
        volumes:
            - symfony_volume:/var/www/symfony
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    memcached:
        build:
            context: .
            dockerfile: ./memcached/1.4/Dockerfile
        depends_on:
            - fluentd
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
    mysql:
        build:
            context: .
            dockerfile: ./mysql/5.7/Dockerfile
        depends_on:
            - fluentd
        volumes:
            - mysql_volume:/var/lib/mysql
        ports:
            - $SYMDOCK_MYSQL_PORT:3306
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
        environment:
            MYSQL_ROOT_PASSWORD: root
    rabbitmq:
        build:
            context: .
            dockerfile: ./rabbitmq/3.6-management/Dockerfile
        depends_on:
            - fluentd
        volumes:
            - rabbitmq_volume:/var/lib/rabbitmq
        ports:
            - $SYMDOCK_RABBITMQ_NODE_PORT:5672
            - $SYMDOCK_RABBITMQ_MANAGER_PORT:15672
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
    elasticsearch:
        build:
            context: .
            dockerfile: ./elasticsearch/1.7/Dockerfile
        depends_on:
            - fluentd
        volumes:
            - elasticsearch_volume:/usr/share/elasticsearch/data
        ports:
            - $SYMDOCK_ELASTICSEARCH_API_PORT:9200
            - $SYMDOCK_ELASTICSEARCH_SERVICE_PORT:9300
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
    kibana:
        build:
            context: .
            dockerfile: ./kibana/4.4/Dockerfile
        depends_on:
            - elasticsearch_logs
        ports:
            - $SYMDOCK_KIBANA_PORT:5601
    fluentd:
        build:
            context: .
            dockerfile: ./fluentd/0.12.26/Dockerfile
        depends_on:
            - elasticsearch_logs
        ports:
            - $SYMDOCK_FLUENTD_PORT:24224
        volumes:
            - fluentd_volume:/fluentd/log
    elasticsearch_logs:
        build:
            context: .
            dockerfile: ./elasticsearch/2.2/Dockerfile
        volumes:
            - elasticsearch_logs_volume:/usr/share/elasticsearch/data
        ports:
            - $SYMDOCK_ELASTICSEARCH_LOGS_API_PORT:9200
            - $SYMDOCK_ELASTICSEARCH_LOGS_SERVICE_PORT:9300
    phpmyadmin:
        build:
            context: .
            dockerfile: ./phpmyadmin/4.5.5/Dockerfile
        depends_on:
            - mysql
            - fluentd
        ports:
            - $SYMDOCK_PHPMYADMIN_PORT:80
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data

volumes:
    symfony_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $SYMDOCK_SYMFONY_VOLUME_PATH
    nginx_volume:
        driver: local
    mysql_volume:
        driver: local
    rabbitmq_volume:
        driver: local
    elasticsearch_volume:
        driver: local
    elasticsearch_logs_volume:
        driver: local
    fluentd_volume:
        driver: local
