version: "2"

services:
    nginx:
        image: $COMPOSE_PROJECT_NAME/nginx:1.9
        volumes:
            - symfony_volume:/var/www/symfony
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    php:
        image: $COMPOSE_PROJECT_NAME/php:5.6
        volumes:
            - symfony_volume:/var/www/symfony
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    memcached:
        image: $COMPOSE_PROJECT_NAME/memcached:1.4
    mysql:
        image: $COMPOSE_PROJECT_NAME/mysql:5.7
    rabbitmq:
        image: $COMPOSE_PROJECT_NAME/rabbitmq:3.6-management
    elasticsearch:
        image: $COMPOSE_PROJECT_NAME/elasticsearch:1.7
    kibana:
        image: $COMPOSE_PROJECT_NAME/kibana:4.4
    fluentd:
        image: $COMPOSE_PROJECT_NAME/fluentd:0.12.26
    elasticsearch_logs:
        image: $COMPOSE_PROJECT_NAME/elasticsearch_logs:2.2
    phpmyadmin:
        image: $COMPOSE_PROJECT_NAME/phpmyadmin:4.5.5
        build:
            context: .
            dockerfile: ./phpmyadmin/4.5.5/Dockerfile
        depends_on:
            - mysql
            - fluentd
        ports:
            - $SYMDOCK_PHPMYADMIN_PORT:80
        logging:
            driver: fluentd
            options:
                fluentd-address: "localhost:$SYMDOCK_FLUENTD_PORT"
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data

volumes:
    symfony_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $SYMDOCK_SYMFONY_VOLUME_PATH
