version: "2"
services:
    symfony:
        build:
            context: .
            dockerfile: ./symfony/ubuntu-15.10/Dockerfile
        tty: true
        volumes:
            - ../symfony:/var/www/symfony
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    nginx:
        build:
            context: .
            dockerfile: ./nginx/1.9/Dockerfile
        links:
            - php
            - fluentd
        volumes_from:
            - symfony
        volumes:
            - ../data/nginx:/var/lib/nginx
        ports:
            - 8080:80
        logging:
            driver: fluentd
            options:
                fluentd-tag: "nginx.docker.{{.Name }}"
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    memcached:
        build:
            context: .
            dockerfile: ./memcached/1.4/Dockerfile
    php:
        build:
            context: .
            dockerfile: ./php/5.6/Dockerfile
            #dockerfile: ./php/7/Dockerfile
            #dockerfile: ./hhvm/latest/Dockerfile
        volumes_from:
            - symfony
        links:
            - mysql
            - memcached
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    node:
        build:
            context: .
            dockerfile: ./node/wheezy/Dockerfile
        tty: true
        volumes_from:
            - symfony
        links:
            - memcached
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    ruby:
        build:
            context: .
            dockerfile: ./ruby/2.3/Dockerfile
        tty: true
        volumes_from:
            - symfony
        links:
            - memcached
        environment:
            SYMDOCK_HOST_UID: $SYMDOCK_HOST_UID
            SYMDOCK_HOST_GID: $SYMDOCK_HOST_GID
            SYMDOCK_CONTAINER_USER: www-data
            SYMDOCK_CONTAINER_GROUP: www-data
    mysql:
        build:
            context: .
            dockerfile: ./mysql/5.7/Dockerfile
        ports:
            - 3306:3306
        volumes:
            - ../data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    rabbitmq:
        build:
            context: .
            dockerfile: ./rabbitmq/3.6-management/Dockerfile
        volumes:
            - ../data/rabbitmq:/var/lib/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
    elasticsearch:
        build:
            context: .
            dockerfile: ./elasticsearch/2.2/Dockerfile
        mem_limit: 2g
        memswap_limit: 2g
        volumes:
            - ../data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            ES_HEAP_SIZE: 2g
    kibana:
        build:
            context: .
            dockerfile: ./kibana/4.4/Dockerfile
        links:
            - elasticsearch
        ports:
            - 5601:5601
    fluentd:
        build:
            context: .
            dockerfile: ./fluentd/latest/Dockerfile
        links:
            - elasticsearch
        ports:
            - 24224:24224
        volumes:
            - ../logs/fluentd:/fluentd/log